### ISSUE TITLE
Linux error prevents updating available releases

### ISSUE THREAD

**Issue by samytichadou** [DotBow/Blender-Version-Manager#18] opened 2020-01-15 10:41 UTC
Hi thanks for the linux version ! looks great so far (tray and launching works perfectly!)
I'm not sure when does it come from, but i'm stuck with the installed version for now (which i manually downloaded before downloading BVM), no update of the available releases
![Capture d’écran de 2020-01-15 11-39-16](https://user-images.githubusercontent.com/26276003/72427305-bf702100-378b-11ea-8f75-6685196d83c0.png)

I launched it in a terminal to catch this error :
```
Uncaught exception
Traceback (most recent call last):
  File "check_for_updates.py", line 35, in run
  File "_strptime.py", line 571, in _strptime_time
  File "_strptime.py", line 359, in _strptime
ValueError: time data 'Tue, 14 Jan 2020 23:08:32 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'
```

Cheers and thanks for your work on this wonderful tool !

**Comment by DotBow** [comment] 2020-01-26 15:53
Duplicate of issue #13, please check it for more information.

**Closed as completed by DotBow** 2020-01-26 15:53 UTC
Labels: bug, linux
